version: "3.7"

services:
  web:
    image: 2hog/docker-training-samples-micro-django
    entrypoint: ./bin/wait-for-db
    command: ./bin/migrate-and-serve
    secrets:
      - database_url
      - secret_key
      - greeting_app_url
      - greeting_app_user
      - greeting_app_password
      - content_app_url
      - content_app_user
      - content_app_password
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost}
  
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

secrets:
  database_url:
    external: true
    name: micro-django-database-url
  secret_key:
    external: true
    name: micro-django-secret-key
  greeting_app_url:
    external: true
    name: micro-django-greeting-app-url
  greeting_app_user:
    external: true
    name: micro-django-greeting-app-user
  greeting_app_password:
    external: true
    name: micro-django-greeting-app-password
  content_app_url:
    external: true
    name: micro-django-content-app-url
  content_app_user:
    external: true
    name: micro-django-content-app-user
  content_app_password:
    external: true
    name: micro-django-content-app-password