version: "3.7"

services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      SECRET_KEY: ${SECRET_KEY:-thisshouldstaysecretforchristssake}
      GREETING_APP_URL: ${GREETING_APP_URL:-http://greeting:4567/}
      GREETING_APP_USER: ${GREETING_APP_USER:-paris}
      GREETING_APP_PASSWORD: ${GREETING_APP_PASSWORD:-kasidiaris}
      CONTENT_APP_URL: ${CONTENT_APP_URL:-http://content:5000/}
      CONTENT_APP_USER: ${CONTENT_APP_USER:-antonis}
      CONTENT_APP_PASSWORD: ${CONTENT_APP_PASSWORD:-kalipetis}
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000

  greeting:
    image: 2hog/docker-training-samples-micro-sinatra
    environment:
      AUTH_USER: ${GREETING_APP_USER:-paris}
      AUTH_PASSWORD: ${GREETING_APP_PASSWORD:-kasidiaris}

  content:
    image: 2hog/docker-training-samples-micro-flask
    environment:
      AUTH_USER: ${CONTENT_APP_USER:-antonis}
      AUTH_PASSWORD: ${CONTENT_APP_PASSWORD:-kalipetis}

  builder:
    image: node:10.9
    command: yarn run dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app

volumes:
  postgres_data:

secrets:
  database_url:
    external: true
    name: micro-django-database-url
  secret_key:
    external: true
    name: micro-django-secret-key
  greeting_app_url:
    external: true
    name: micro-django-greeting-app-url
  greeting_app_user:
    external: true
    name: micro-django-greeting-app-user
  greeting_app_password:
    external: true
    name: micro-django-greeting-app-password
  content_app_url:
    external: true
    name: micro-django-content-app-url
  content_app_user:
    external: true
    name: micro-django-content-app-user
  content_app_password:
    external: true
    name: micro-django-content-app-password