version: "3.7"

services:
  web:
    image: 2hog/docker-training-samples-micro-django
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      SECRET_KEY: ${SECRET_KEY:-thisshouldstaysecretforchristssake}
      GREETING_APP_URL: ${GREETING_APP_URL:-http://greeting:4567/}
      GREETING_APP_USER: ${GREETING_APP_USER:-paris}
      GREETING_APP_PASSWORD: ${GREETING_APP_PASSWORD:-kasidiaris}
      CONTENT_APP_URL: ${CONTENT_APP_URL:-http://content:5000/}
      CONTENT_APP_USER: ${CONTENT_APP_USER:-antonis}
      CONTENT_APP_PASSWORD: ${CONTENT_APP_PASSWORD:-kalipetis}
    entrypoint: ./bin/wait-for-db
    command: ./bin/migrate-and-serve
  
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}