apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: docker-training-samples-postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: docker-training-samples-postgres