apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-training-samples-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-training-samples-postgres
  template:
    metadata:
      labels:
        app: docker-training-samples-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: docker-training-samples-micro-django-secret
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docker-training-samples-micro-django-secret
                  key: postgres_password
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: docker-training-samples-micro-django-secret
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: docker-training-samples-micro-django-secret
                  key: postgres_db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-volume-claim