apiVersion: v1
kind: Service
metadata:
  name: docker-training-samples-micro-django
spec:
  type: NodePort
  selector:
    app: docker-training-samples-micro-django
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
